import json
from pathlib import Path

import pytest

from agentic_testops import cli
from agentic_testops.llm import (
    LlmRequestError,
    MissingApiKeyError,
    explain_failures,
)
from agentic_testops.models import AuditReport, Diagnosis, Failure, LlmExplanation, TestRun
from agentic_testops.reporter import render_markdown


def _report() -> AuditReport:
    failure = Failure(
        nodeid="tests/test_app.py::test_case",
        headline="AssertionError: assert 'a' == 'b'",
        error_type="AssertionError",
        detail="E   AssertionError: assert 'a' == 'b'",
    )
    diagnosis = Diagnosis(
        failure=failure,
        category="behavioral-regression",
        confidence="medium",
        summary="Assertion failed.",
        evidence=["E   AssertionError: assert 'a' == 'b'"],
    )
    return AuditReport(
        project_path=Path("demo"),
        run=TestRun(
            command=["python", "-m", "pytest"],
            cwd=Path("."),
            returncode=1,
            stdout="FAILED tests/test_app.py::test_case - AssertionError\n",
            stderr="",
            duration_seconds=0.1,
        ),
        failures=[failure],
        diagnoses=[diagnosis],
    )


def _anthropic_response(text: str) -> dict:
    return {"content": [{"type": "text", "text": text}]}


def test_explain_failures_parses_json_response() -> None:
    captured = {}

    def fake_transport(payload, api_key, timeout):
        captured["payload"] = payload
        captured["api_key"] = api_key
        return _anthropic_response(
            json.dumps(
                [
                    {
                        "nodeid": "tests/test_app.py::test_case",
                        "explanation": "The implementation returns 'a' but the test expects 'b'.",
                        "fix_outline": "Update the return value computation.",
                    }
                ]
            )
        )

    explanations = explain_failures(_report(), api_key="key-123", transport=fake_transport)

    assert captured["api_key"] == "key-123"
    assert "tests/test_app.py::test_case" in captured["payload"]["messages"][0]["content"]
    assert explanations == [
        LlmExplanation(
            failure_nodeid="tests/test_app.py::test_case",
            explanation="The implementation returns 'a' but the test expects 'b'. Fix: Update the return value computation.",
            model="claude-haiku-4-5",
        )
    ]


def test_explain_failures_requires_api_key(monkeypatch) -> None:
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)

    with pytest.raises(MissingApiKeyError):
        explain_failures(_report())


def test_explain_failures_keeps_prose_when_model_ignores_json() -> None:
    def fake_transport(payload, api_key, timeout):
        return _anthropic_response("The failure looks like a simple value mismatch.")

    explanations = explain_failures(_report(), api_key="key", transport=fake_transport)

    assert len(explanations) == 1
    assert explanations[0].failure_nodeid == "(entire report)"
    assert "value mismatch" in explanations[0].explanation


def test_explain_failures_rejects_empty_response() -> None:
    def fake_transport(payload, api_key, timeout):
        return {"content": []}

    with pytest.raises(LlmRequestError):
        explain_failures(_report(), api_key="key", transport=fake_transport)


def test_explain_failures_parses_fenced_json() -> None:
    fenced = '```json\n[{"nodeid": "n", "explanation": "x", "fix_outline": ""}]\n```'

    def fake_transport(payload, api_key, timeout):
        return _anthropic_response(fenced)

    explanations = explain_failures(_report(), api_key="key", transport=fake_transport)

    assert explanations[0].failure_nodeid == "n"
    assert explanations[0].explanation == "x"


def test_markdown_report_renders_llm_section() -> None:
    report = _report()
    from dataclasses import replace

    report = replace(
        report,
        llm_explanations=[
            LlmExplanation(failure_nodeid="tests/test_app.py::test_case", explanation="Root cause.", model="m")
        ],
    )

    text = render_markdown(report)

    assert "## LLM Analysis" in text
    assert "Advisory analysis generated by `m`" in text
    assert "Root cause." in text


def test_json_report_includes_llm_explanations() -> None:
    from dataclasses import replace

    report = replace(
        _report(),
        llm_explanations=[LlmExplanation(failure_nodeid="n", explanation="e", model="m")],
    )

    payload = report.to_dict()

    assert payload["llm_explanations"] == [{"failure_nodeid": "n", "explanation": "e", "model": "m"}]


def test_cli_skips_llm_analysis_without_api_key(monkeypatch, tmp_path, capsys) -> None:
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)

    def fake_run_pytest(project_path: Path, extra_args=None, timeout=120):
        return TestRun(
            command=["python", "-m", "pytest"],
            cwd=project_path,
            returncode=1,
            stdout="FAILED tests/test_app.py::test_case - AssertionError: assert False\n",
            stderr="",
            duration_seconds=0.1,
        )

    monkeypatch.setattr(cli, "run_pytest", fake_run_pytest)

    exit_code = cli.main(["audit", str(tmp_path), "--llm-explain", "-o", str(tmp_path / "report.md")])

    assert exit_code == 1
    assert "LLM analysis skipped" in capsys.readouterr().out
    assert "## LLM Analysis" not in (tmp_path / "report.md").read_text(encoding="utf-8")


def test_cli_includes_llm_analysis_with_fake_explainer(monkeypatch, tmp_path) -> None:
    def fake_run_pytest(project_path: Path, extra_args=None, timeout=120):
        return TestRun(
            command=["python", "-m", "pytest"],
            cwd=project_path,
            returncode=1,
            stdout="FAILED tests/test_app.py::test_case - AssertionError: assert False\n",
            stderr="",
            duration_seconds=0.1,
        )

    def fake_explain(report, model="claude-haiku-4-5"):
        return [LlmExplanation(failure_nodeid="tests/test_app.py::test_case", explanation="Why.", model=model)]

    monkeypatch.setattr(cli, "run_pytest", fake_run_pytest)
    monkeypatch.setattr(cli, "explain_failures", fake_explain)

    exit_code = cli.main(
        [
            "audit",
            str(tmp_path),
            "--llm-explain",
            "--llm-model",
            "test-model",
            "-o",
            str(tmp_path / "report.md"),
            "--json-output",
            str(tmp_path / "report.json"),
        ]
    )

    assert exit_code == 1
    report_text = (tmp_path / "report.md").read_text(encoding="utf-8")
    assert "## LLM Analysis" in report_text
    assert "Why." in report_text
    payload = json.loads((tmp_path / "report.json").read_text(encoding="utf-8"))
    assert payload["llm_explanations"][0]["model"] == "test-model"
